---

- name: Fetch laurel binary
  get_url:
    url: "{{ auditd_laurel_url }}"
    dest: "{{ install_archives }}/{{ auditd_laurel_url | basename }}"
    checksum: "{{ auditd_laurel_checksum | default(omit) }}"
    mode: '0644'

- name: Unarchive laurel binary
  unarchive:
    src: "{{ install_archives }}/{{ auditd_laurel_url | basename }}"
    dest: "/usr/local/sbin"
    mode: '0755'
    remote_src: yes
    include: laurel
    creates: "/usr/local/sbin/laurel"

- name: Add laurel user
  user:
    name: "{{ auditd_laurel_user }}"
    home: /var/log/laurel
    create_home: yes
    system: yes

- name: Ensure /etc/laurel directory exists
  file:
    path: /etc/laurel
    state: directory
    mode: '0755'

- name: Set laurel configuration
  template:
    src: "{{ auditd_laurel_config }}"
    dest: /etc/laurel/config.toml
    mode: '0644'

- name: Set laurel audit plugin configuration
  template:
    src: "{{ auditd_laurel_plugin }}"
    dest: /etc/audisp/plugins.d/laurel.conf
    mode: '0644'
  notify:
    - restart auditd
    - restart auditd - rhel7+
