---
- name: Ensure rsyslog is present
  ansible.builtin.package:
    name: rsyslog
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Ensure audispd-plugins is present
  ansible.builtin.package:
    name: "{{ audisp_pkg }}"
    state: present
  register: plugins_result
  until: plugins_result is success

- name: Ensure audispd base directory exists
  ansible.builtin.file:
    dest: "{{ audisp_syslog_target | dirname }}"
    state: directory
    mode: '0755'
    owner: "{{ syslog_user }}"
    group: "{{ syslog_group | default('root') }}"
  when:
    - "'/var/log/' in audisp_syslog_target"
    - audisp_syslog_target | dirname != '/var/log'

- name: Setup rsyslog to send audisp logs to a specific target
  ansible.builtin.template:
    src: rsyslog-audispd.conf.j2
    dest: /etc/rsyslog.d/30-audispd.conf
    mode: '0644'
    backup: "{{ auditd_backup | default(false) }}"
    validate: 'rsyslogd -N2 -f %s'
  notify:
    - Restart rsyslog

- name: Ensure audisp syslog plugin is disabled
  community.general.ini_file:
    path: "{{ auditd_plugins }}/syslog.conf"
    section: null
    option: "{{ item.o }}"
    value: "{{ item.v }}"
    mode: '0640'
    backup: "{{ auditd_backup | default(false) }}"
  loop:
    - { o: "active", v: "no" }
    - { o: "direction", v: "out" }
    - { o: "path", v: "/sbin/audisp-syslog" }
    - { o: "type", v: "always" }
    - { o: "args", v: "LOG_INFO" }
    - { o: "format", v: "string" }
  notify:
    - Restart auditd
    - Restart auditd - rhel7+

- name: Add logrotate configuration for audispd log
  ansible.builtin.template:
    src: logrotate-audispd.j2
    dest: /etc/logrotate.d/audispd
    mode: '0644'
    validate: 'logrotate -dv %s'
