---
name: AnsibleCI

on:
  push:
  pull_request:
  schedule:  # run weekly, every monday 03:00
    - cron: '0 3 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
    env:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks

    steps:
      - uses: actions/checkout@v2
        with:
          path: juju4.auditd
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint flake8 yamllint
      - name: yamllint
        run: |
          yamllint .
      - name: yamllint
        run: |
          ansible-lint
      - name: run test
        run: |
          pwd
          find -ls
          cd $GITHUB_WORKSPACE/juju4.auditd && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: idempotency run
        run: |
          cd $GITHUB_WORKSPACE/juju4.auditd && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 1)
      - name: On failure
        run: |
          systemctl -l --no-pager status auditd
        with:
          # status: ${{ env.WORKFLOW_CONCLUSION }}  # neutral, success, skipped, cancelled, timed_out, action_required, failure
          status: failure
        if: env.WORKFLOW_CONCLUSION == 'failure'  # notify only if failure
      - name: After script
        run: |
          sudo ls /etc/audit/rules.d
          sudo cat /etc/audit/audit.rules
          sudo auditctl -l
          cat /etc/rsyslog.d/30-audisp.conf
          sudo cat /etc/audisp/plugins.d/syslog.conf
          sudo tail -100 /var/log/audit/audit.log
